### ISSUE TITLE
Provide values override for `global.clusterRouterBase`

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-operator#4]
In the helm chart install instructions we require the following step:

https://github.com/janus-idp/helm-backstage/tree/main/charts/backstage#installing-from-the-chart-repository

When installed on OpenShift via this operator, this should be automated:

1. Make the operator fetch `oc get ingresses.config/cluster -o jsonpath={.spec.domain}`
2. Provide this via [`reconciler.WithOverrideValues`](https://github.com/janus-idp/backstage-operator/blob/4e1629579e0670965f5be9757ad070a8d3d1fd76/main.go#L128C7-L128C7)

Please make the operator to always enforce this value to be in sync with the cluster - The operator doesn't need to watch the `ingresses.config/cluster` resource, but it should fetch the correct value on every helm upgrade.

**Comment by kadel** [comment]
> 2\. Provide this via [`reconciler.WithOverrideValues`](https://github.com/janus-idp/backstage-operator/blob/4e1629579e0670965f5be9757ad070a8d3d1fd76/main.go#L128C7-L128C7)

I'm not sure if using `WithOverridValues` is the right thing. With this approach, the values will only be updated when the operator starts. I'm unable to figure out how to update values for `WithOverridValues` on every helm upgrade. 


I think that there should be a little bit more than just simply overriding  `global.clusterRouterBase`.

For example, users might want to set their own custom `clusterRouterBase` that doesn't match the default Ingress domain.
I'm considering the approach where `global.clusterRouterBase` is set only when the user has not set it explicitly.
